### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [sashacravcenco/grid_template#1]
1)
код невалидный
![image](https://user-images.githubusercontent.com/8464662/98293599-48747500-1fb7-11eb-9437-d636b9dc9e9f.png)

2)
оформление не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/98293741-7d80c780-1fb7-11eb-829e-a0fca82b191c.png)

**Comment by sashacravcenco** [comment]
https://github.com/sashacravcenco/grid_template.git

https://sashacravcenco.github.io/grid_template/

чт, 5 нояб. 2020 г. в 22:39, Andrey <notifications@github.com>:

**Comment by sashacravcenco** [comment]
Внесла правки
